language: cpp
dist: trusty
matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libstdc++-7-dev']
    - os: linux
      addons:
        apt:
          sources:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - ./bin/libtest
